package com.example.zzz;

import androidx.appcompat.app.AppCompatActivity;

import android.app.DatePickerDialog;
import android.content.Intent;
import android.os.Bundle;
import android.text.InputType;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayDeque;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

public class CreateTask extends AppCompatActivity {
    DatePickerDialog datePiker;
    EditText editText;

    TextView taskId;
    private EditText taskName, taskDescription, taskDueDate;
    private Spinner taskPriority;
    FirebaseDatabase mDatabase;
    DatabaseReference taskdbReference;
    FirebaseAuth mAuth;

    String id;
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_create_task);

        taskName = findViewById(R.id.taskName);
        taskDescription = findViewById(R.id.taskDescription);
        taskPriority = findViewById(R.id.priority_spinner);
        taskDueDate = findViewById(R.id.dueDate);
        taskId = findViewById(R.id.taskid);

        mDatabase = FirebaseDatabase.getInstance();
        taskdbReference = mDatabase.getReference("Tasks");
        mAuth = FirebaseAuth.getInstance();

        DatabaseReference pushedPostRef = taskdbReference.push();
        id = pushedPostRef.getKey();
        taskId.setText(id);


        editText=(EditText) findViewById(R.id.dueDate);
        editText.setInputType(InputType.TYPE_NULL);
        editText.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                final Calendar calender = Calendar.getInstance();
                int day = calender.get(Calendar.DAY_OF_MONTH);
                int month = calender.get(Calendar.MONTH);
                int year = calender.get(Calendar.YEAR);
                // date picker dialog
                datePiker = new DatePickerDialog(CreateTask.this,
                        new DatePickerDialog.OnDateSetListener() {
                            @Override
                            public void onDateSet(DatePicker view, int year, int month, int dayOfMonth) {
                                editText.setText(dayOfMonth + "-" + (month + 1) + "-" + year);
                            }
                        }, year, month, day);
                datePiker.getDatePicker().setMinDate(System.currentTimeMillis() - 1000);
                datePiker.show();
            }
        });


    }

    public void taskCreate(View view) {
        // Generate a reference to a new location and add some data using push()


        // Get the unique ID generated by a push()


        String name = taskName.getText().toString();
        String description = taskDescription.getText().toString();
        String priority = taskPriority.getSelectedItem().toString();
        String dueDate = taskDueDate.getText().toString();
        String status = "To Do";
        String assignedTo = "None";

        if(name.isEmpty()){

            Toast.makeText(this, "Task Name cannot be empty", Toast.LENGTH_SHORT).show();
        }
        else if (description.isEmpty()){
            Toast.makeText(this, "Task Description cannot be empty", Toast.LENGTH_SHORT).show();
        }

        else if (dueDate.isEmpty()){
            Toast.makeText(this, "Please Select Due Date", Toast.LENGTH_SHORT).show();
        }
        else{
            FirebaseUser currentUser = mAuth.getCurrentUser();

            Task taskObj = new Task(id, name,description, priority,dueDate, currentUser.getEmail(), status, assignedTo);
            taskdbReference.child(id).setValue(taskObj);

            startActivity(new Intent(this, dashboard.class));
            finish();

        }
    }
}
